#!/usr/bin/env python
#
# Created by Jeremy Bowman on Thu Feb 12 15:44:13 EST 2015
# Copyright (c) 2015 Safari Books Online. All rights reserved.
#
# This script is always run from the project root

import os
import shlex
import subprocess
    

def popen(cmd):
    args = shlex.split(cmd)
    return subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).stdout

diff = popen('git diff --name-only HEAD@{1} HEAD')
changed_files = {filename.strip() for filename in diff}

if any('git-hooks' in f for f in changed_files):
    # update git hooks
    os.system('git-hooks/install-hooks')

# always delete pyc files
print 'Deleting .pyc files in project dir'
os.system("find . -name '*pyc' -delete")

virtual_env = os.environ.get('VIRTUAL_ENV')
if virtual_env:
    python = os.path.join(virtual_env, 'bin', 'python')

    # put stuff that requires virtualenv here

    # delete all .pyc files in the virtual env
    print 'Deleting .pyc files in virtualenv'
    os.system("find %s -name '*pyc' -delete" % virtual_env)

    os.system("pip install setuptools==11.0")
    os.system("pip install pip==6.0.6")
    os.system("pip install --disable-pip-version-check --requirement requirements/tests.txt")
    os.system("pip install --disable-pip-version-check --editable ./")
